### ISSUE TITLE
[Request] Add methods to Geom that check for circular collisions

### ISSUE THREAD

**Issue by nachoverdon** [TerryCavanagh/haxegon#175]
To check collision between circles, circles and boxes, etc...
Checking between circles is kinda easy. It's something like this (pseudocode):
```
var circle1: Circle = {x: 5, y: 5, radius: 20};
var circle2: Circle = {x: 10, y: 5, radius: 15};

// Returns true if circles are overlaping
function Geom.incircle(circle1: Circle, circle2: Circle): Bool {
    var dx = circle1.x - circle2.x;
    var dy = circle1.y - circle2.y;
    var distance = Math.sqrt(dx * dx + dy * dy);

    return distance < circle1.radius + circle2.radius;
}

Geom.incircle(circle1, circle2); // true
```

**Comment by TerryCavanagh** [comment]
Yeah, have been considering adding a few things like that! Want to avoid making classes for shapes like Circle and Rectangle, though, since I think that's a particular layer of complexity that throws beginners a lot.

Anyway, yep, I'll add a few of these to the next build.

**Comment by nachoverdon** [comment]
Well, to be honest, I think classes would help a lot.

I ended up 'classifying' a Circle shape so that it handle's its own parameters (x, y, radius...) and then it has a public method .draw() (to be called on a scene's update()) that just performs a Gfx.drawcircle() using its parameters, because it was easier to keep the code organized mostly. So maybe having shape classes by default can be helpful. HyperHaxegon!

**Comment by TerryCavanagh** [comment]
Haha, yep, I get the temptation.

**Comment by TerryCavanagh** [comment]
So... looking at this a bit more, I think I've decided that it's not really worth it. Things like circle v circle collisions are pretty simple (as you point out!) - and it's a lot of extra cruft for the library, which is supposed to be lightweight and minimal by design.

Like, if I added circle v circle and circle v rect collision functions, I go from having:

``` haxe
Geom.overlap(); //rect v rect
```

to having

``` haxe
Geom.rectoverlap(); //rect v rect
Geom.circleoverlap(); //circle v circle
Geom.rectcircleoverlap(); //circle v rect
```
Also, why stop there? Line collisions versus shapes would be handy too, as would basic physics, etc etc.

I think the right answer here is to write an extension (https://github.com/TerryCavanagh/haxegon/issues/103).
