### ISSUE TITLE
add the fonts from zeedonk

### ISSUE THREAD

**Issue by increpare** [TerryCavanagh/haxegon#56]

**Comment by TerryCavanagh** [comment]
Ok, two options here:

*(1) Embed the fonts in the library, so that you just have access to all of them.*

So, I just embedded the "default" font in the library, and it works great, and is ok size wise (15kb)! I *could* do the same for the rest of the zeedonk font set! That might be nice, having a bunch of fonts available in a haxegon project without messing around with assets. It might add a lot of weight to the project (maybe 200kb-300kb, maybe less if I pack the textures and compress the xml), but it's one of those features that's genuinely very nice to have in a library...

*(2) Keep the library lightweight, and just have the fonts easily accessible from somewhere*

Just include a example that has all the fonts, or link to them on the website, or something else. Avoids the issue of bulking up the library.

I'm not sure. Anyone want to weigh in on this?

**Comment by TerryCavanagh** [comment]
The key thing to investigate here is whether or not I can make the embedded fonts -DCE friendly - if the engine doesn't include the files for fonts you're not using, then it's obviously worth doing. If not, it probably isn't.

**Comment by TerryCavanagh** [comment]
Ok, this isn't needed anymore. Closing!
